# -*- coding: utf-8 -*-
"""dse6000_covid_housing_eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UBMPTEzlupsHea_oSlQhmLUF9j2Dl6Hc

# Covid Housing EDA

Observations from the World Bank Covid Housing data set.

**By: Alec Rospierski**

*Last Update: 3-11-2022*
"""

import pandas as pd
import numpy as np
from google.colab import drive
import seaborn as sns
import matplotlib.pyplot as plt

"""# Load Data"""

# Statement #1
df = pd.read_csv('https://storage.googleapis.com/computing-bucket/covid_data.csv', encoding='ISO-8859-1')

# Statement #2
df.columns

"""# Quick Look at Data"""

# Statement #3
df.describe()

# Statement #4
# Find missing values
df.isna().sum()

# Statment #5
df.dtypes

# Statement #6
df.shape

pd.set_option('display.max_colwidth', None)

"""### Summary of Above Findings

Looking at the columns available, it seems as though there are many that are not needed for analysis. Anything to do with survey information should be deleted. Additionally, there are three different identifiers for region. Below, one of these identifiers are deleted in its entirety. I'll use the region code and a dictionary mapping to the long form of the region for easier reference. The same thing will be done for the code column which is a country code.

"""

# Statment #7
# Drop un-needed columns
ch_df = df.drop(['survey_producer', 'survey_link', 'last_updated', 'row_id'], axis=1)

# Statement #8
country_code_mapper = dict(ch_df[['code', 'country']].drop_duplicates().to_numpy())
country_code_mapper

region_mapper = dict(ch_df[['region_code', 'region']].drop_duplicates().to_numpy())
region_mapper

# Drop full name columns
fin_df = ch_df.drop(['region', 'country'], axis=1)

"""# Summary Statistics

In this section I want to find the average value of each of the different indicators across all collected samples. 
"""

# Statment #9
# Length of the unique indicators
len(fin_df['indicator'].unique())

# Statment #10
summary_stats_pt = pd.pivot_table(fin_df, values=['indicator_val'], index=['indicator', 'indicator_display'], aggfunc=np.mean)

summary_stats_pt

# Statment #11
unq_indicators = fin_df[['indicator', 'indicator_display']].drop_duplicates().reset_index(drop=True)
unq_indicators

fin_df['unit_measure'].unique()

"""# Percentage of Respondents per Area Type"""

area_df = fin_df[['indicator', 'indicator_val', 'urban_rural']]

# Statment #12
area_df = area_df[area_df['indicator'].str.contains('Demo_educ')]

area_pt = pd.pivot_table(area_df, values=['indicator_val'], index=['urban_rural', 'indicator'], aggfunc=np.mean).reset_index()
educ_mapper = {'Demo_educ1': 'No Education',
               'Demo_educ2': 'Any Primary',
               'Demo_educ3': 'Any Secondary',
               'Demo_educ4': 'Any Post Secondary'}
area_pt['indicator'] = area_pt['indicator'].apply(lambda x: educ_mapper[x])

area_pt

sns.set(rc={'figure.figsize':(15,8)})
# Statment #13
ax = sns.barplot(x='urban_rural', y='indicator_val', hue='indicator', data=area_pt)
ax.set(title='Percentage of Respondents per Education Level in Differing Areas', xlabel='Area of Country', ylabel='% of Respondents')
ax.legend(loc='upper left')
plt.show()

"""### Summary

This bar plot shows the percentage of respondents with different levels of education in the different areas of the surveyed countries. Clearly, most participants in the surveyed regions have at least any type of secondary education. What's more interesting is that the rural population has a higher secondary education than the urban population. Upon closer inspection, one will notice that all percentages for each "area" add up to 100%. Therefore, the urban population still has more people with higher levels of education, as expected. It can also be seen that those with no education or even just primary education are more prevalent in urban areas.

# Catplots Observing Relationships between Conflict Zones, Income Status, Medical Need, and Financial Access
"""

# Statement #14
fin_df['FCS'] = fin_df['FCS'].fillna('None')
fin_df['FCS'].unique()

cat_df = fin_df[['indicator', 'indicator_val', 'FCS', 'income_group']]

cat_df = cat_df[(cat_df['indicator'] == 'Heal_need') | (cat_df['indicator'] == 'Fina_access')]
# Statment #15
cat_df['indicator'] = cat_df['indicator'].apply(lambda x: 'Need Med. Assistant' if x == 'Heal_need' else 'Financial Access')

ax = sns.catplot(data=cat_df, x='indicator', y='indicator_val', hue='income_group', col='FCS', col_wrap=3)
ax.fig.subplots_adjust(top=0.9) 
ax.fig.suptitle('Exploring Conflict Zones, Financial Access and Medical Assistance within Income Groups')

"""### Summary

Here we can see the relationships between income groups, financial access and medical assistance, and conflict zones. In the high intensity conflict graph, we can see that there are more people who need medical assitance than have access to financials (ATMs and banks). Another interesting aspect of this particular corner of the plot is that it only includes people in the low income group. In general we can see that with higher intensity conflicts, more people need medical assitance. However, in areas with no conflict, there is a lot more people and a much larger range of medical assistance. Furthermore, in the area with no conflict, it appears that people with a lower income tend to need more medical assistance. Lastly, in general the areas surveyed seem to have low access to financial institutions.

# Distribution for GDP Per Capita per % Taken any Preventative Measure
"""

gdp_df = fin_df[['indicator', 'indicator_val', 'GDP_pc']]
gdp_df = gdp_df.rename(columns={'indicator_val': 'Preventative Measure', 'GDP_pc': 'GDP / Capita'})

gdp_df = gdp_df[gdp_df['indicator'] == 'Prev_AP_other']

gdp_df

sns.set(rc={'figure.figsize':(15,8)})
ax = sns.displot(x='GDP / Capita', y='Preventative Measure', data=gdp_df, bins=10)
ax.set(title='Distribution of Preventative Measures per GDP / Capita')

"""### Summary

The distribution plot above shows the relationship between a country's GDP per capita and the overall preventative measures taken by its citizens. It is clear that people that live in a country with a higher GDP took more preventative measures than those who live lower GDP countries. However, there appears to be a large concentration of preventative measures taken in lower GDP countries. This is likely a result from more countries with lower GDPs being represented in the survey. Looking at the higher GDPs, we notice that over 90% of citizens took preventative measures.

# Violin Chart of Income Group & Vaccination Rates & Know about Gov. Intervention
"""

vac_df = fin_df[['indicator_val', 'indicator', 'income_group']]

vac_df = vac_df[(vac_df['indicator'] == 'Vac_done') | (vac_df['indicator'] == 'Know_any')]
vac_df['indicator'] = vac_df['indicator'].apply(lambda x: 'Known Gov. Intv.' if x == 'Know_any' else 'Vaccinated')

# Know_any = Aware of any government action due to COVID-19 - 7 comparable categories (% of respondents)
ax = sns.violinplot(data=vac_df, x='income_group', y='indicator_val', hue='indicator', split=True)
ax.set(title='% of Respondents Per Income Group Vaccinated and Know of any Gov. Intervention', xlabel='Income Group', ylabel='% of Respondents')

"""### Summary

The violin graph above explores the relationship between income groups, known government intervention, and vaccination status. In all of the income groups, there appears to be a high percentage of people that know about their governments' intervention following the covid-19 pandemic. However, the vaccination statuses do not follow the same trend. There appears to be a low vaccination rate in the lower income groups than in higher income groups. However, even the high income citizens are not all vaccinated.

# Overall Insights

Overall, there are clearly many different causes and effects within the given data set. Observing the above graphs it appears that some of the strongest effects come from the financial situation of the countries. Additionally, the education of the citizens may play a key part. In further analysis, it would be interesting to dive into the relationships between vaccination status, income group, and education level. It would seem that countries with a higher GDP and more people in higher income groups would be more likely to take preventative measures such as being vaccinated.
"""

